### ISSUE TITLE
[REQUEST] Add support for INES 2.0 header support

### ISSUE THREAD

**Issue by TheRealHamtaro126** [nicklausw/asm6n#2]
Hey there, Is there any way you can add INES 2.0 header support to ASM6N? This program will get better to use if so.

**Comment by nicklausw** [comment]
This fork is deprecated in favor of asm6f, could you make this issue over there?
 https://github.com/freem/asm6f

In terms of the feature request, how do you want it implemented? Perhaps like tepples does it in his macro pack? http://wiki.nesdev.com/w/index.php/NES_2.0_header_for_ca65

**Comment by TheRealHamtaro126** [comment]
Sent a request to ASM6F's Issue report page, Thanks!

This issue is now Closed.
